    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/api/video-to-audio/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Role: !GetAtt ConvertVideoToAudioLambdaRole.Arn
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          SOURCE_BUCKET_NAME: !Sub "${VideoBucketName}"
          DESTINATION_BUCKET_NAME: !Sub "${AudioBucketName}"
          MEDIA_CONVERT_DEFAULT_IAM_ROLE_ARN: !GetAtt MediaConvertDefaultRole.Arn
          AWS_MEDIA_CONVERT_ENDPOINT: !Sub "https://mediaconvert.${AWS::Region}.amazonaws.com"
      Events:
        !Include ./convertVideoToAudioLambdaEvents.yaml