    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/api/translate-transcription/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Role: !GetAtt TranslateTranscriptionLambdaRole.Arn
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          SOURCE_BUCKET_NAME: !Sub "${TranscriptionBucketName}"
          DESTINATION_BUCKET_NAME: !Sub "${TranslationBucketName}"
          TRANSLATION_TARGET_LANGUAGE_CODE: !Ref TranslationTargetLanguageCode
      Events:
        !Include ./translateTranscriptionLambdaEvents.yaml